### ISSUE TITLE
Connection to jira time's out shortly. require re-login multiple times

### ISSUE THREAD

**Issue by khaledbnmohamed** [mohamed-abdul-fattah/jira-logger#37]
The issue appear after using the `connect` command and add your credentials.

In a short period around 1~2 hours, credentials expire and have to re-login again.
It would be much better if I can login only once and tokens doesn't expire

I'd love to help out on this feature.

**Comment by mohamed-abdul-fattah** [comment]
According to Altassian documentation for [Jira REST authentication](https://developer.atlassian.com/cloud/jira/platform/jira-rest-api-cookie-based-authentication/#cookie-expiration)
>One disadvantage of using cookies compared to basic authorization is that they expire. You have probably noticed this when accessing Jira through a web browser. Every once in a while, especially if you have not used Jira in a while, you need to log in again because your cookie has expired. The same phenomenon occurs when using REST. 
If you use REST with a cookie that has expired, you will receive a 401 error response from Jira. The response body will contain a message telling you that your cookie is invalid. At that point, you will need to re-authenticate to the session resource on the "auth" API.

Unfortunately, there is no much to do, and this issue will be closed. A working trick I use to avoid re-authentication multiple time is to `log:sync` once at the end of the working day.
Happy coding.
